kafka:
  image: flozano/kafka:0.9.0.0
  ports:
    - "2181:2181"
    - "9092:9092"
  environment:
    ADVERTISED_HOST: 192.168.99.100
elasticsearch:
  image: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"